### PR TITLE
XK: Rewrite tha data model

### LINKED ISSUE #150: Rewrite the datamodel
1. Sustainability (#68) - add it to research data (see templates/project_proposal.json)
2. Keywords (will solve #89, #90, #105 )
3. Cooperation (#46, #89) - should we add it as the 4. category to relations (next to child, parent, sibling)?
4. Topic relations - should they be removed and added as a keyword category in line with the DHA topic ["Type"](https://vocabs.dariah.eu/dha_taxonomy/en/page/?uri=https%3A%2F%2Fvocabs.acdh.oeaw.ac.at%2Fdhataxonomy%2FCollection06)?

### PR DESCRIPTION
**Pull request by XeniaMonika**
Closes #150

### CODE REVIEW

**Comment by XeniaMonika** [comment]
I have changed the schema with this one. Should we document it somehow?

**Comment by XeniaMonika** [comment]
And I probably should change the schema version to 0.1.7, right?

**Comment by theodore-s-beers** [comment]
Yeah, we should stay in the habit of bumping the schema version when we make changes to it. And maybe at our next meeting (this coming week?) we can talk more about our plans for the schema.

**Comment by XeniaMonika** [comment]
Ok, let's do it!

**Pull request merged**
