### PR TITLE
Xk: add new projects 

### PR DESCRIPTION
**Pull request by XeniaMonika**

### CODE REVIEW

**Comment by theodore-s-beers** [comment]
@Jomula, is the status quo that CI fails on every one of these PRs because the JSON validation workflow needs to be updated?

**Comment by XeniaMonika** [comment]
I will try to take care of it this week

**Comment by theodore-s-beers** [comment]
I was also looking into it. Just haven't had much time lately due to conferences/workshops.

**Comment by XeniaMonika** [comment]
It´s working now :D

**Pull request merged**
