### PR TITLE
Fix typos etc.

### PR DESCRIPTION
**Pull request by theodore-s-beers**

### CODE REVIEW

**Comment by theodore-s-beers** [comment]
@XeniaMonika, sorry for all the extra noise in this commit due to JSON reformatting. I just wanted to fix a few typos that I noticed (e.g., "sexteenth" → "sixteenth").

You once mentioned that you use a Python script that auto-formats all of the JSON files. Would you mind sharing what tool that is? I wouldn't mind running it whenever I've made edits. Alternatively, we could think about setting up a formatter whose configuration lives in the repo. That would make it easier to ensure that different contributors are following the same workflow.

**Comment by XeniaMonika** [comment]
Yes, I also think it´d be a good idea to have such a formatter! I don´t use any specific tool, but my script is built in a way, that any time I add a change it iterates over all files, and actually rewrites them. The thing that changes the formatting is simply this:
with open(full_path_3, 'w', encoding = "utf8") as f:
  json_string=json.dumps(projects_json,ensure_ascii=False, indent=2)
  f.write(json_string)
  f.close()
Maybe it is not the best workflow but I wrote it in the beginning when the DB was still relatively small. I use it mostly to automatize as many things as I can (e. g. long and lat values, child-parent-sibling relations, alphabetic order of keywords and so on). If you want I can show it you and maybe we can think about a better workflow.

**Comment by theodore-s-beers** [comment]
That's fine. It just means that we've been using the JSON formatting provided by default in Python.

With your consent, I'm going to make a substantial change: there will be an NPM package manifest for the `master` branch. I'm currently using it only to install a dev dependency, Prettier, which is a good formatter that works for many file types (incl. JSON, JS, HTML, CSS, and Markdown).

There will be one large commit that affects the formatting of most of our files. Then, in the future, any contributor can keep things consistent by installing the NPM dependencies (`npm install`) and running the format command (`npm run format`).

**Comment by XeniaMonika** [comment]
I will save the project and add him as a contact person. By the way, contacting the projects is also something we should talk about on Monday. 
And wow! How did you find this info so quickly? I was looking for so long but I couldn´t find anything about this project, haha!

Sure, lets do it this way. 
Is that what you mean? https://github.com/prettier/prettier/blob/main/docs/install.md
I´m not sure if I understood how will it work. Should I also install Prettier locally?

**Comment by XeniaMonika** [comment]
Sure, lets do it this way. 
Is that what you mean? https://github.com/prettier/prettier/blob/main/docs/install.md
I´m not sure if I understood how will it work. Should I also install Prettier locally?

**Comment by XeniaMonika** [comment]
Ah, ok. You´ve added this two json files to the master, I guess they would do the job, so I don´t have to install it locally, right? It will reformat automatically after every PR?  Did I get it right?

**Comment by theodore-s-beers** [comment]
You won't need to install Prettier specifically. I've already set up an NPM package manifest that specifies it as a dependency.

Once you've merged the changes that I made to the repo this morning, you should see a file called `package.json`. I'm using that to say, basically, "This project uses Prettier as a dependency, and the `format` script should run the following command…"

So then, if you have [Node.js](https://nodejs.org/) installed—and NPM, its package manager, which comes included—you can run a couple simple commands to get up to speed with the new workflow. Use `npm install` to install any dependencies, then `npm run format`.

I'm sorry if this is a lot to grapple with all at once!

**Comment by XeniaMonika** [comment]
Ok, got it! 
That´s fine! I´m always happy when something new comes up!

**Comment by theodore-s-beers** [comment]
Cool. Let me know if you have any questions. It wouldn't be a bad idea for us to go over a few workflow details at our next in-person meeting, whenever that happens.

Node/NPM is worth learning. People complain about the ecosystem, with good reason, but the reality is that it's incredibly dominant in web-oriented software development.

**Pull request merged**
