### PR TITLE
Fill in missing dates

### PR DESCRIPTION
**Pull request by theodore-s-beers**

### CODE REVIEW

**Comment by theodore-s-beers** [comment]
@XeniaMonika, I realized that there were some projects for which we didn't record a start date. I think that's a datum that we should always include, even if it requires a judgment call or a bit of guesswork. So I've done my best to fill in this field in cases where it was empty. Our schema validation will also mandate this from now on. Let me know if you have any thoughts—or if you can come up with better estimates of the start dates of some projects. Thanks as always.

**Comment by XeniaMonika** [comment]
Ok. I used to leave this field in case there was no Info provided, bsc I wanted to avoid biased information. But maybe for our goals an approximate is better than nothing when based on some solid info provided by the project. I´m also asking myself what we want to do with this date except for the timeline. It could be important if we want to investigate the availability of the research data after a given project expires.  If we want to include it in our future publication, we should mention that some of the starting dates are approximated.

**Comment by XeniaMonika** [comment]
We could also need it for a general investigation of the field, e.g. for how many years such projects receive funding, how shorter or longer projects deal with their long-term data availability, what is their general life cycle, how the field developed in the recent years, and stuff like that.  So in this case is it better to have an estimate that could be wrong, or nothing at all? The second option could also mean that we won't have enough data. And one question, how did you come up with these dates?

**Comment by XeniaMonika** [comment]
And maybe we could use the comment section to mark that the date is estimated

**Comment by theodore-s-beers** [comment]
Yeah, we can be open about the fact that some start dates are approximate. Using the `comment` field to note this is also a good idea. Just to preserve my thought process, let me list here the projects for which I added or changed start dates in this PR, and in each case, the basis on which I did so.

1. A Digital Typology of Arabic Documents: This falls under the umbrella of the Arabic Papyrology Database, which I'm fairly confident was launched in 2003. So I gave the start date of the parent project to this child project. That's definitely not correct—the Digital Typology is described as the "latest phase" of the APD—but it's the best I could come up with. **To be marked as approximate**

2. al-Ṯurayyā Project: The website's description of who has worked on the project, and when, gives the clear impression that 2013 was the first year. **No need to mark as approximate**

3. Arabic and Latin Corpus: I found a relevant [YouTube video](https://www.youtube.com/watch?v=w6v3XlKpgVs) whose description indicates a start year of 2016. **No need to mark as approximate**

4. Arabic Papyrology Database: Start date revised to 2003 based on information on their website. I'm not sure why this was previously recorded as 2004. **No need to mark as approximate**

5. Study of Averroes's Long Commentary on the Physics in Hebrew and Latin Transmission: The parent project, Averroes Editions, is known to have started in 2016 with a funding period of twenty-five years. And one of the postdocs who worked on this subproject, Grégory Clesse, was there from 2016 to 2019. **No need to mark as approximate**

6. Critical Edition of the Fragmentary Latin Translation of Averroes's Commentary on De Partibus Animalium and De Generatione Animalium: Basically the same situation here. Clesse is listed as having worked on this edition, and he joined the Averroes Editions project in its first year. **No need to mark as approximate**

7. Critical Edition of Ibn Bāğğa's Commentary on Aristotle's De generatione et corruptione: This edition was actually published in 2021. So I think we can use that as the end year, and 2016 as the start year (inherited from Averroes Editions). **No need to mark as approximate**

8. Critical Edition of Ibn Bāǧǧa's Commentary on Aristotle's Physics: The then-postdoc who worked on this edition, [Farah Cherif-Zahar](https://philosophie.univ-paris8.fr/farah-cherif-zahar), notes that she was with the project from October 2016 to August 2017. I opted to leave the end date of the edition blank, since I don't know whether it's complete. **No need to mark as approximate**

9. eScriptorium: This project has a [German Wikipedia entry](https://de.wikipedia.org/wiki/EScriptorium) that lists an "Erscheinungsjahr" of 2018. So I went with that. **No need to mark as approximate**

10. Historical Middle East Data Alliance: The earliest activity in this GitHub organization (to which I belong) was in 2020. I'm just about certain that was when Nathan Gibson set it up. **No need to mark as approximate**

11. HMML: Both their website and Wikipedia list the year of founding as 1965. Does this not work for our purposes? **No need to mark as approximate**

12. Isnalyser: The GitHub repo was initialized in 2019. I think it's ok to use that as a start date. **No need to mark as approximate**

13. KompetenzwerkD: Newsletters published by the project suggest that it started ca. February 2020. **No need to mark as approximate**

14. Mesopotamian Royal Inscriptions: This is a tough one. I gave it the start year of its parent project, the Cuneiform Digital Library Initiative (2000). **To be marked as approximate**

15. Mesopotamian Seals: Same as above. I couldn't find a start date for this specific project, so I used 2000, the start date of the CDLI as a whole. **To be marked as approximate**

16. Nimrud NW Palace: Same as above. I couldn't find a start date for this specific project, so I used 2000, the start date of the CDLI as a whole. **To be marked as approximate**

17. Open Arabic Periodical Editions: I found an [article by Till](https://www.digitalhumanities.org/dhq/vol/16/2/000593/000593.html) in which he dates the founding of this project to August 2015. **No need to mark as approximate**

18. Oracc: I spent an embarrassingly long time trying to pin down a start date for this project. 2012 was the best estimate I could come up with, looking at things like when they established their social media accounts. **To be marked as approximate**

19. Publikationsdienst für wissenschaftliche Datenmodelle und Vokabulare: The funding of this project had specific start and end dates. **No need to mark as approximate**

20. Sefaria: The [Wikipedia entry](https://en.wikipedia.org/wiki/Sefaria) indicates a year of founding of 2011—though, on different bases, one could make an argument for 2012 or even 2013. I wouldn't fuss over it. **No need to mark as approximate**

21. SHARIAsource: This project appears to have been set up, or at least scaled up, based on grants awarded in 2015. There was some publicity at the time. **No need to mark as approximate**

22. Syriaca.org: Thomas A. Carlson seems to have been the first postdoc to work on this project, and he started in 2012. I'm not sure how well that works as a proxy for the start date of the project itself, but it's the best information that I found. **To be marked as approximate**

23. Tikkoun Sofrim: 2018 is an estimate based on the earliest activity in their blog. **To be marked as approximate**

By my count, there are seven projects whose start dates should be labeled approximate: A Digital Typology of Arabic Documents; Mesopotamian Royal Inscriptions; Mesopotamian Seals; Nimrud NW Palace; Oracc; Syriaca.org; and Tikkoun Sofrim. @XeniaMonika, does this make sense to you? Thanks.

**Comment by theodore-s-beers** [comment]
Ok, I've added comments to those seven files. Feel free to continue reviewing our data, making fixes as needed, etc. It's an ongoing process. But from now on, our schema validation will reject any entry that doesn't have a start date.

**Comment by XeniaMonika** [comment]
Ok, great job! Thank you! I´m impressed with how many dates you have found!

**Pull request merged**
