### PR TITLE
Xk

### PR DESCRIPTION
**Pull request by XeniaMonika**

### CODE REVIEW

**Comment by theodore-s-beers** [comment]
@XeniaMonika, the GitHub UI will remind you after you merge a PR that the merged branch is now safe to delete. I think it's a good practice to do that, to keep the repo's branch list clean.

It might also be helpful to give PRs slightly more descriptive titles (your short commit messages already look good).

**Comment by XeniaMonika** [comment]
@theodore-s-beers, sure I can do it this way.

**Comment by theodore-s-beers** [comment]
I wouldn't worry too much about writing an actual description for a PR, if what it's doing is clear from the PR title and the commit message(s). Things can get a bit confusing, given how many places there are to add notes. There are short commit messages (which is what you've been doing, if I understand correctly). You can also add longer commit messages. Then, on GitHub, we have the PR title field and the PR description.

What I think is a good baseline is to use short commit messages and a descriptive PR title. That doesn't cost much time and is often enough, unless there are more detailed things to be documented or discussed. @Jomula may have other thoughts.

**Comment by Jomula** [comment]
I agree, as long as it was only Xenia and me working on the project I guess it was sufficient to just ignore the PR message, but as there are more people involved now, a descriptive PR title would be nice.

**Comment by XeniaMonika** [comment]
Ok, my mistake @theodore-s-beers, I misread your message and thought that you meant PR descriptions. From now on I will be adding a PR title

**Pull request merged**
