### PR TITLE
Xk: Finish keywords, add new projects 

### PR DESCRIPTION
**Pull request by XeniaMonika**

### CODE REVIEW

**Comment by theodore-s-beers** [comment]
@XeniaMonika, are there now keywords to replace all of the categories? Or are we not replacing some of them because they weren't very descriptive? The only category for which I can find an obvious equivalent keyword is `rdm`.

**Comment by XeniaMonika** [comment]
rdm is research_data_management. And yes, replacing them is what I would propose. DH and NLP are useless, bcs they relate to almost all projects, infrastructure is research_infrastucture and we don´t have any single meta-project. What I also thinking about, is how to  more clearly differentiate between research and infrastructure project - I am still not happy with the "type" category of DHA taxonomy.

**Comment by theodore-s-beers** [comment]
Ok, I've removed all display of categories in the new front end. It's cleaner, anyway, to think of keywords/tags as opposed to boolean values for categories that a given project does or does not fit. That always struck me as a bit odd.

**Comment by theodore-s-beers** [comment]
I guess at this point, I would make that whole section optional in the schema. Then we can stop adding it for new entries, and CI should still pass. Once we're totally comfortable with the new system, we can maybe get rid of the old categories.

**Pull request merged**
